version: "3"

services:
  workspace:
    image: tianon/true
    container_name: dnmp-www
    volumes:
      - ./www:/usr/share/nginx/html

  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "8088:80"
      - "4433:443"
    links: 
      - php-fpm:php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:/usr/share/nginx/html
    env_file:
      - .env
  
  php-fpm:
    # 这里的args 是属于 build 下面的,用于构建./php-fpm/Dockerfile 文件中 ARG 参数指定 php 版本
    build: 
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: dnmp-php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini

volumes:
  local_data:
    driver: local