version: "3"

services:
  workspace:
    image: tianon/true
    container_name: dnmp-www
    volumes:
      - ./www:/usr/share/nginx/html

  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "8088:80"
      - "4433:443"
    links: 
      - php-fpm:php-fpm
    volumes:
      - ./www:/usr/share/nginx/html
    env_file:
      - .env
  
  php-fpm:
    build: ./php-fpm
    container_name: dnmp-php-fpm

volumes:
  local_data:
    driver: local