version: "2.1"

services:
  www:
    image: tianon/true
    container_name: lnmp-www
    volumes:
      - ./www:/usr/share/html

  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - www
    # networks: 
    #   web_server_network:
    #     ipv4_address: $(NGINX_WEB_SERVER_IP)
    env_file:
      - .env

# networks:
#   web_server_network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         subnet: "${WEB_SERVER_SUBNET}"
#         gateway: "${WEB_SERVER_GATEWAY}"